from dataclasses import dataclass


@dataclass
class P3DX_Robot:

    def move(self, velocity: int): ...

    def rotate(self, angularVelocity: int): ...

    def step(self, timeStep: int): ...

    def stop(self): ...

    def getActualPose(self) -> tuple[float, float]: ...
