from dataclasses import dataclass


@dataclass
class TwoWheelRobotBase:

    def move_wheels(self, v_right, v_left): ...

    def step(self, timeStep): ...

    def state(self): ...

    def reset(self): ...

    def shutdown(self): ...
